# Generated by Django 4.0.5 on 2022-09-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp22', '0003_remove_blogpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
