# Generated by Django 4.0.5 on 2022-09-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp22', '0005_remove_blogpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
