# Generated by Django 4.0.5 on 2022-09-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp22', '0006_alter_blogpage_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpage',
            new_name='Medicine',
        ),
    ]
