# Generated by Django 4.0.5 on 2022-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp22', '0007_rename_blogpage_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='status',
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
